apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts
          name: jenkins
          ports:
            - containerPort: 8080
              name: jenkins
            - containerPort: 50000
              name: jenkins-log
          resources: {}
          volumeMounts:
            - name: jenkins-home-volume
              mountPath: /var/jenkins_home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: jenkins-home-volume
          hostPath:
            path: /var/lib/pv/jenkins
status: {}
