apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins-log
  namespace: devops
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
status:
  loadBalancer: {}
