apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
  namespace: devops
spec:
  ports:
  - port: 8080
    name: jenkins
    protocol: TCP
    targetPort: 8080
    nodePort: 32100
  - port: 50000
    name: jenkins-log
    protocol: TCP
    targetPort: 50000
  - port: 32122
    name: jenkins-ssh
    protocol: TCP
    nodePort: 32122
    targetPort: 32122
  selector:
    app: jenkins
  type: NodePort
status:
  loadBalancer: {}
