apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: backup
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - apt update; apt install -y rclone mysql-client;
                  rclone moveto --no-check-certificate OpenDrive:/OracleCloud/oracle3-pv/pv.tgz OpenDrive:/OracleCloud/oracle3-pv/pv-old.tgz;
                  mysqldump -h bookstackdb.bookstack -u bookstack -p"<yourdbpass>" bookstackapp > /var/lib/pv/bookstack/bookstackapp.dump;
                  mysqldump -h websitedb.website -u websitedb -p"websitedb" websitedb > /var/lib/pv/website/config/websitedb.dump;
                  tar zcv /var/lib/pv | rclone rcat --no-check-certificate OpenDrive:/OracleCloud/oracle3-pv/pv.tgz
              image: ubuntu
              name: backup
              resources:
                requests:
                  ephemeral-storage: "10Gi"
                limits:
                  ephemeral-storage: "10Gi"
              volumeMounts:
                - name: pv
                  mountPath: /var/lib/pv
                - name: rclone-volume
                  mountPath: /root/.config/rclone/
          restartPolicy: Never
          volumes:
            - name: pv
              hostPath:
                path: /var/lib/pv
            - name: rclone-volume
              secret:
                secretName: rclone-secret