apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: backup
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - apt update; apt install -y mysql-client;
                  apt install -y /var/lib/pv/rclone-v1.59.2-linux-arm64.deb;
                  rclone moveto --no-check-certificate OpenDrive:/OracleCloud/oracle3-pv/pv.tgz OpenDrive:/OracleCloud/oracle3-pv/pv-old.tgz;
                  mysqldump -h bookstackdb.bookstack --column-statistics=0 -u bookstack -p"<yourdbpass>" bookstackapp > /var/lib/pv/bookstack/bookstackapp.dump;
                  mysqldump -h websitedb.website --column-statistics=0 -u websitedb -p"websitedb" websitedb > /var/lib/pv/website/config/websitedb.dump;
                  rclone copy -P --transfers=20 --checkers=20 --no-check-certificate --local-no-check-updated /var/lib/pv/ OpenDrive:/OracleCloud/oracle3-pv/
              image: ubuntu
              name: backup
              resources:
                requests:
                  ephemeral-storage: "10Gi"
                limits:
                  ephemeral-storage: "10Gi"
              volumeMounts:
                - name: pv
                  mountPath: /var/lib/pv
                - name: rclone-volume
                  mountPath: /root/.config/rclone/
          restartPolicy: Never
          volumes:
            - name: pv
              hostPath:
                path: /var/lib/pv
            - name: rclone-volume
              secret:
                secretName: rclone-secret