apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookstackweb
  name: bookstackweb
  namespace: bookstack
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30100
  selector:
    app: bookstackweb
  type: NodePort
status:
  loadBalancer: {}
