apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookstackdb
  name: bookstackdb
  namespace: bookstack
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: bookstackdb
status:
  loadBalancer: {}
