apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
  namespace: database
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 32306
  type: NodePort
  selector:
    app: mysql
status:
  loadBalancer: {}
