apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rundeck
  name: rundeck
  namespace: automation
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 32306
  type: NodePort
  selector:
    app: rundeck
status:
  loadBalancer: {}
