apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rundeck
  name: rundeck
  namespace: automation
spec:
  ports:
  - port: 4443
    protocol: TCP
    targetPort: 4443
    nodePort: 32440
  type: NodePort
  selector:
    app: rundeck
status:
  loadBalancer: {}
