apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rundeck
  name: rundeck
  namespace: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rundeck
    spec:
      containers:
      - image: homelabs/rundeck
        name: rundeck
        ports:
        - containerPort: 4440
        volumeMounts:
          - name: "etc"
            mountPath: "/etc"
          - name: "var-lib-rundeck"
            mountPath: "/var/lib/rundeck"
        resources: {}
      volumes:
        - name: "etc"
          hostPath:
            path: /var/lib/pv/rundeck/etc
        - name: "var-lib-rundeck"
          hostPath:
            path: /var/lib/pv/rundeck/var_lib_rundeck
status: {}
