apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: metabase
  name: metabase
  namespace: tools
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30300
  selector:
    app: metabase
  type: NodePort
status:
  loadBalancer: {}
