apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: websiteweb
  name: websiteweb
  namespace: website
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30200
  selector:
    app: websiteweb
  type: NodePort
status:
  loadBalancer: {}
