apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: websitedb
  name: websitedb
  namespace: website
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: websitedb
status:
  loadBalancer: {}
