apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: websiteweb
  name: websiteweb
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websiteweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: websiteweb
    spec:
      containers:
      - image: wordpress
        name: websiteweb
        volumeMounts:
          - name: "html"
            mountPath: "/var/www/html"
          - name: "apache2"
            mountPath: "/etc/apache2"
        resources: {}
      volumes:
        - name: "html"
          hostPath:
            path: /var/lib/pv/website/html
        - name: "apache2"
          hostPath:
            path: /var/lib/pv/website/apache2
status: {}

